api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import QuestionsViewSet, UsersViewSet, AnswerViewSet

router = routers.DefaultRouter()
router.register('questions', QuestionsViewSet)
router.register('users', UsersViewSet)
router.register('answers', AnswerViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('med.urls')),
    path('', include('accounts.urls')),
    path('', IndexView.as_view(), name='index'),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med/urls.py
from django.urls import path

from med.views.comment_views import CommentDeleteView, CommentListView, CommentModerationView, QuestionListView
from med.views.info_page import AboutMeView, OnlineConsultationView, OfflineConsultationView, AboutClubView
from med.views.photo_views import (
    PhotoCreateView, PhotoListView, PhotoDeleteView,
    PhotoDetailView, PhotoUpdateView
)

from med.views.search_view import search_view
from med.views.video_views import (
    VideoDetailView, Videos,
    AdminVideosList, VideoUpdate, VideoDeleteView
)

from med.views.article_views import (
    ArticleDeleteView, ArticleUpdateView, ArticleCreateView,
    ArticleDetailView, ArticleListView
)

from med.views.category_views import (
    CategoryListView, CategoryCreateView, CategoryDeleteView,
    CategoryEditView, CategoryArticleListView, CategoryPhotoListView,
    CategoryVideoListView
)


app_name = 'med'

urlpatterns = [
    # Video
    path('video/<int:pk>/', VideoDetailView.as_view(), name='video_detail'),
    # path('video/create/', VideoCreateView.as_view(), name='video_create'),
    path('videos/unpublished/', AdminVideosList.as_view(), name='videos_unpublished'),
    path('videos/', Videos.as_view(), name='videos'),
    path('video/<int:pk>/update/', VideoUpdate.as_view(), name='video_update'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='video_delete'),

    # Article
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),

    # Category
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category/<int:pk>/edit', CategoryEditView.as_view(), name='category_update'),
    path('category/<int:pk>/article/list', CategoryArticleListView.as_view(), name='category_article_list'),
    path('category/<int:pk>/photo/list', CategoryPhotoListView.as_view(), name='category_photo_list'),
    path('category/<int:pk>/video/list', CategoryVideoListView.as_view(), name='category_video_list'),

    # Photo
    path('photo/create', PhotoCreateView.as_view(), name='photo_create'),
    path('photo/list', PhotoListView.as_view(), name='photo_list'),
    path('photo/<int:pk>/delete', PhotoDeleteView.as_view(), name='photo_delete'),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
    path('photo/<int:pk>/update', PhotoUpdateView.as_view(), name='photo_update'),

    # Comment
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete'),
    path('comments/list', CommentListView.as_view(), name='comment_list'),
    path('questions/list', QuestionListView.as_view(), name='questions_list'),
    path('comment/<int:pk>/detail', CommentModerationView.as_view(), name='comment_detail'),

    # Others
    path('search/', search_view, name='search'),
    path('about_me/', AboutMeView.as_view(), name='about_me'),
    path('online_consultation/', OnlineConsultationView.as_view(), name='online_consultation'),
    path('offline_consultation/', OfflineConsultationView.as_view(), name='offline_consultation'),
    path('about_club/', AboutClubView.as_view(), name='about_club'),
]

accounts/views/profile_views.py
import logging

from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse

from django.views.generic import CreateView, UpdateView, DetailView, ListView, TemplateView
from med.helpers import get_age

from accounts.forms import (
    MyUserCreationForm, PasswordChangeForm, ProfileUpdateForm, UserUpdateForm
)
from accounts.views.helpers import AdminPermissionsView

from accounts.models import Profile
from med.models import Category, Comment, Answer


logger = logging.getLogger('main')


class RegisterView(CreateView):
    model = User
    template_name = 'accounts/user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        date_birth = self.request.POST.get('birth_date')
        phone = self.request.POST.get('phone')
        instagram = self.request.POST.get('instagram')
        if date_birth == '' or phone == '' or instagram == '':
            return self.form_invalid(form)
        else:
            user = form.save()
            logger.info(f'Пользователь id{user.pk} зарегистрировался.')
            Profile.objects.create(
                user=user,
                birth_date=self.request.POST.get('birth_date'),
                phone=phone,
                personal_consultation=self.request.POST.get('personal_consultation'),
                instagram=instagram
            )
            login(self.request, user)
            return redirect('profile', pk=user.pk)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, data=self.request.POST))


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'accounts/user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('login')

    def test_func(self):
        return self.request.user == self.get_object()


class ProfileView(UserPassesTestMixin, DetailView):
    model = get_user_model()
    context_object_name = 'user_obj'
    template_name = 'profile/profile_view.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['questions'] = Comment.objects.filter(is_question=True, author=self.object)
        context['answers'] = Answer.objects.all()
        context['profile'] = Profile.objects.all()
        # context['user_id'] = self.kwargs.get('pk')

        age = get_age(self.object.profile.birth_date)
        context['age'] = age
        return context

    def test_func(self):
        return self.get_object() == self.request.user \
               or self.request.user.is_superuser or self.request.user.profile.is_admin


class ProfileEdit(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm
    template_name = 'profile/profile_update.html'
    context_object_name = 'user_obj'

    def get(self, request, *args, **kwargs):
        if request.user.pk == kwargs.get('pk'):
            return super(ProfileEdit, self).get(request, *args, **kwargs)
        else:
            wrong_id = kwargs.get('pk')
            logger.warning(f'Пользователь id-{request.user.pk} пытался редактировать профиль пользователя id-{wrong_id}.')
            raise Http404

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
            kwargs['birth_date'] = str(self.get_object().profile.birth_date)
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileUpdateForm(**form_kwargs)

    def get_success_url(self):
        return reverse('profile', kwargs={'pk': self.object.pk})


class QuestionsView(ListView):
    template_name = 'profile/users_questions.html'
    context_object_name = 'questions'

    def get_queryset(self):
        user_id = self.kwargs.get('pk')
        return Comment.objects.filter(author=user_id, is_question=True)

    def get(self, request, *args, **kwargs):
        if request.user.pk == kwargs.get('pk') or request.user.profile.is_admin:
            return super(QuestionsView, self).get(request, *args, **kwargs)
        else:
            wrong_id = kwargs.get('pk')
            logger.warning(f'Пользователь id-{request.user.pk} пытался просматривать вопросы пользователя id-{wrong_id}.')
            raise Http404

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QuestionsView, self).get_context_data()
        context['answers'] = Answer.objects.all()
        context['user_obj'] = User.objects.get(id=self.kwargs.get('pk'))
        return context


class RenewSubscriptionView(LoginRequiredMixin, TemplateView):
    template_name = 'profile/renew_subscription.html'


class SubscriptionView(TemplateView):
    template_name = 'profile/subscription.html'

templates/profile/categories_sidebar.html
<div class="flex_wrapp">
    <button class="btn btn-green btn-sm width-100" type="button" data-bs-toggle="offcanvas"
            data-bs-target="#categories-sidebar" aria-controls="categories-sidebar">
        {{ btn_text }}
    </button>
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="categories-sidebar" aria-labelledby="sidebar-head">
    <div class="offcanvas-header sidebar-header">
        <h5 id="sidebar-head">Список категорий</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body">

        <form method="post">
            {% csrf_token %}
            <div class="flex-wrapp">
                <input type="submit" name="categories_change" class="btn btn-sm btn-green" value="Сохранить">
            </div>

            {% for category in categories %}
                {% if category in user_obj.profile.categories.all %}

                    <div class="form-check">
                        <div class="card text_center">
                            <input class="form-check-input" checked name="categories" value="{{ category.pk }}" type="checkbox" id="{{ category.pk }}">
                            <label class="form-check-label" for="{{ category.pk }}">{{ category.title }}</label>
                        </div>
                    </div>

                {% endif %}
            {% endfor %}

            {% for category in categories %}
                {% if category not in user_obj.profile.categories.all %}

                    <div class="form-check">
                        <div class="card text_center">
                            <input class="form-check-input" name="categories" value="{{ category.pk }}" type="checkbox" id="{{ category.pk }}">
                            <label class="form-check-label" for="{{ category.pk }}">{{ category.title }}</label>
                        </div>
                    </div>

                {% endif %}
            {% endfor %}
        </form>
    </div>
</div>

templates/profile/med_admin.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}
{% endblock navbar %}

{% block content %}
    <div class="container page-container">
        <table class="table">
          <thead>
            <tr>
              <th scope="col" style="width: 30%">Контент</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td><a href="{% url 'all_users' %}"><b>Все пол-и ({{ users_count }})</b></a></td>
                <td><a href="{% url 'paid_users' %}">Активные ({{ paid_users_count }})</a></td>
                <td><a href="{% url 'unpaid_users' %}">Не продлили подписку ({{ unpaid_users_count }})</a></td>
            </tr>
            <tr>
                <td><a href="{% url 'med:videos' %}"><b>Видео ({{ videos_count }})</b></a></td>
                <td><a href="{% url 'med:videos_unpublished' %}"><i class="bi bi-plus"></i> Добавить</a></td>
                <td><a href="{% url 'med:videos' %}"><i class="bi bi-pencil-square"></i> Изменить</a></td>
            </tr>
            <tr>
                <td><a href="{% url 'med:articles' %}"><b>Статьи ({{ articles_count }})</b></a></td>
                <td><a href="{% url 'med:article_create' %}"><i class="bi bi-plus"></i> Добавить</a></td>
                <td><a href="{% url 'med:articles' %}"><i class="bi bi-pencil-square"></i> Изменить</a></td>
            </tr>
            <tr>
                <td><a href="{% url 'med:photo_list' %}"><b>Картинки ({{ photos_count }})</b></a></td>
                <td><a href="{% url 'med:photo_create' %}"><i class="bi bi-plus"></i>Добавить</a></td>
                <td><a href="{% url 'med:photo_list' %}"><i class="bi bi-pencil-square"></i> Изменить</a></td>
            </tr>
            <tr>
                <td><a href="{% url 'med:comment_list' %}"><b>Комменты ({{ comments_count }}) {% if new_comments %} <span style="color: green">(новых - {{ new_comments }})</span> {% endif %} </b></a></td>
                <td></td>
                <td><a href="{% url 'med:comment_list' %}"><i class="bi bi-pencil-square"></i> Модерация</a></td>
            </tr>
            <tr>
                <td><a href="{% url 'med:comment_list' %}"><b>Вопросы ({{ questions_count }}) {% if new_questions %} <span style="color: green">(новых - {{ new_questions }})</span> {% endif %} </b></a></td>
                <td></td>
                <td><a href="{% url 'med:questions_list' %}"><i class="bi bi-pencil-square"></i> К списку</a></td>
            </tr>

          </tbody>
        </table>
    </div>

{% endblock %}

templates/profile/paid_users.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}
{% endblock navbar %}

{% block content %}
    <div class="container page-container">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Username</th>
              <th scope="col">Имя Фамилия</th>
              <th scope="col">Дата рег-и</th>
            </tr>
          </thead>
          <tbody>

        {% for user in paid_users %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'profile' user.user.pk %}">{{ user.user.username }}</a></td>
                <td>{{ user.user.first_name }} {{ user.user.last_name }}</td>
                <td>{{ user.created_at| date }}</td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}

templates/profile/profile_update.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Редактирование профиля
{% endblock %}

{% block navbar %}
    {% include 'partial/navigation_new.html' %}
{% endblock navbar %}

{% block content %}
    <div class="title-center">
        <h1>Редактировать данные</h1>
    </div>
    <img class="ellipse-14" src="{% static 'bg-elements/ellipse-14.svg' %}" alt="ellipse-14">
    <img class="ellipse-13" src="{% static 'bg-elements/ellipse-13.svg' %}" alt="ellipse-13">
    <form action="{% url 'profile_edit' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <div class="avatar">
                {% if user_obj.profile.avatar %}
                    <img class="avatar-photo" src="{{ user_obj.profile.avatar.url }}" alt="Аватар">
                {% else %}
                    <div class="no-photo">
                        <img src="{% static 'bg-elements/photo.svg' %}" alt="">
                    </div>
                {% endif %}
            </div>

            <div>
                <label class="input-label" for="name">Имя</label>
            </div>
            <div class="input_div">
                {% if form.errors.first_name %}
                    <input type="text" class="input-style error_border" name="first_name" id="name" value="{{ user_obj.first_name }}" placeholder="Введите имя">
                    <div class="alert errors-list error_style" role="alert">
                        {% for error in form.errors.first_name %}
                            <span>*</span>{{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="text" class="input-style" name="first_name" id="name" value="{{ user_obj.first_name }}" placeholder="Введите имя">
                {% endif %}
            </div>

            <div>
                <label class="input-label" for="last_name">Фамилия</label>
            </div>
            <div class="input_div">
                {% if form.errors.last_name %}
                    <input type="text" class="input-style error_border" name="last_name" id="last_name" value="{{ user_obj.last_name }}" placeholder="Введите фамилию">
                    <div class="alert errors-list error_style" role="alert">
                        {% for error in form.errors.last_name %}
                            <span>*</span>{{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="text" class="input-style" name="last_name" id="last_name" value="{{ user_obj.last_name }}" placeholder="Введите фамилию">
                {% endif %}
            </div>

            <div>
                <label class="input-label" for="phone">Номер телефона</label>
            </div>
            <div class="input_div">
                {% if profile_form.phone.errors %}
                    <input type="tel" class="input-style error_border" name="phone" id="phone" value="{{ user_obj.profile.phone }}"
                           placeholder="Введите номер телефона">
                    <div class="alert errors-list error_style" role="alert">
                        {% for error in profile_form.phone.errors %}
                            <span>*</span>{{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="tel" class="input-style" name="phone" id="phone" value="{{ user_obj.profile.phone }}" placeholder="Введите номер телефона">
                {% endif %}
            </div>

            <div>
                <label class="input-label" for="email">Email</label>
            </div>
            <div class="input_div">
                {% if form.errors.email %}
                    <input type="text" class="input-style error_border" name="email" id="email" value="{{ user_obj.email }}" placeholder="Введите эл.почту">
                    <div class="alert errors-list error_style" role="alert">
                        {% for error in form.errors.email %}
                            <span>*</span>{{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="text" class="input-style" name="email" id="email" value="{{ user_obj.email }}" placeholder="Введите эл.почту">
                {% endif %}
            </div>

            <div>
                <label class="input-label" for="birth_date">Дата рождения</label>
            </div>
            <div class="input_div">
                {% if profile_form.birth_date.errors %}
                    <input type="date" class="input-style error_border" name="birth_date" id="birth_date" value="{{ birth_date }}">
                    <div class="alert errors-list error_style" role="alert">
                        {% for error in profile_form.birth_date.errors %}
                            <span>*</span>{{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="date" class="input-style" name="birth_date" id="birth_date" value="{{ birth_date }}">
                {% endif %}
            </div>

            <div>
                <label class="input-label" for="instagram">Профиль в инстаграм</label>
            </div>
            <div class="input_div">
                {% if profile_form.instagram.errors %}
                    <input type="text" class="input-style error_border" name="instagram" id="instagram" value="{{ user_obj.profile.instagram }}"
                           placeholder="Введите свой инстаграм">
                    <div class="alert errors-list error_style" role="alert">
                        {% for error in profile_form.instagram.errors %}
                            <span>*</span>{{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    <input type="text" class="input-style" name="instagram" id="instagram" value="{{ user_obj.profile.instagram }}" placeholder="Введите свой инстаграм">
                {% endif %}
            </div>

            <div>
                <label class="input-label" for="input__file">Аватар</label>
                <input type="file" name="avatar" id="input__file" class="input input__file" accept="image/*">
                <label for="input__file" class="input__file-button">
                    <span class="input__file-icon-wrapper"><img class="input__file-icon" src="{% static 'bg-elements/plus.svg' %}" alt="Выбрать файл" width="25"></span>
                    <span class="input__file-button-text">Выберите файл</span>
                </label>
            </div>

            <div class="register-btn">
                <button type="submit" class="reg-in">
                    <img src="{% static 'bg-elements/save_btn.svg' %}" alt="ellipse-14">
                </button>
            </div>
        </div>
    </form>

    <script>
    let inputs = document.querySelectorAll('.input__file');
    Array.prototype.forEach.call(inputs, function (input) {
      let label = input.nextElementSibling,
        labelVal = label.querySelector('.input__file-button-text').innerText;

      input.addEventListener('change', function (e) {
        let countFiles = '';
        if (this.files && this.files.length >= 1)
          countFiles = this.files.length;

        if (countFiles)
          label.querySelector('.input__file-button-text').innerText = this.files[0].name;
        else
          label.querySelector('.input__file-button-text').innerText = labelVal;
      });
    });
</script>
{% endblock content %}

templates/profile/profile_view.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Профиль
{% endblock %}


{% block navbar %}
    {% include 'partial/navigation_new.html' %}
{% endblock navbar %}


{% block content %}
    <div class="background bg-profile"></div>
    <div class="main-container page-container">

        <div class="avatar">
            {% if user_obj.profile.avatar %}
                <img class="avatar-photo" src="{{ user_obj.profile.avatar.url }}" alt="Аватар">
            {% else %}
                <div class="no-photo">
                    <img src="{% static 'bg-elements/photo.svg' %}" alt="">
                </div>
            {% endif %}
        </div>

        {% if user.pk == user_obj.pk %}
            <a href="{% url 'profile_edit' pk=user_obj.pk %}" class="edit-link">
                <div class="edit-link-btn">
                    Редактировать
                </div>
            </a>
            <a href="{% url 'user_password_change' pk=user_obj.pk %}">
                <div class="pass-change-btn">
                    Сменить пароль
                </div>
            </a>
        {% endif %}

        <div class="side-menu">

            <a href="{% url 'subscription' %}">
                <div class="subscription">
                    Подписка
                </div>
            </a>

            <a href="{% url 'questions' user_obj.id %}">
                <div class="question">
                    Вопросы
                </div>
            </a>

            <a href="{% url 'profile' user_obj.id %}">
                <div class="private-office">
                    Личный кабинет
                </div>
            </a>

        </div>

        <div class="full-name">
            {{ user_obj.first_name }} {{ user_obj.last_name }}, {{ age }}
            <p>
                {{ user_obj.username }}
            </p>
        </div>

        <div class="info">
            <p>Email - {{ user_obj.email }}</p>
            <p>Дата регистрации - {{ user_obj.date_joined.date }}</p>
            <p>Телефон - {{ user_obj.profile.phone }}</p>
            <p>Инстаграм - {{ user_obj.profile.instagram }}</p>
        </div>

        <a href="#">
            <img src="{% static 'bg-elements/make-review.svg' %}" alt="" class="make-review">
        </a>

    </div>

    <img class="ellipse-24" src="{% static 'bg-elements/ellipse-24.svg' %}" alt="">

{% endblock %}

templates/profile/renew_subscription.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Продление подписки
{% endblock %}

{% block navbar %}
    {% include 'partial/navigation_new.html' %}
{% endblock %}

{% block content %}
    <div class="renew_subscr_background"></div>
    <div class="renew_subscr_container">
        <p class="renew_subscr_title">Действие вашей подписки истекло!</p>
        <a href="#"><img src="{% static 'bg-elements/subscription.svg' %}" alt=""></a>
    </div>
    <img src="{% static 'bg-elements/ellipse_group_5.svg' %}" alt="ellipse" class="ellipse_group_5">
{% endblock %}

templates/profile/subscription.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Подписка в клуб
{% endblock %}


{% block content %}
    <div class="subscription_background"></div>
    <div class="subscription_container">
        <h2 class="subscription_title">Стоимость подписки</h2>
        <div>
            <a href="#" class="subscription_tariff">1 месяц - 490 рублей</a>
            <a href="#" class="subscription_tariff subscription_tariff2">3 месяца - 1250 рублей</a>
        </div>
        <div>
            <p class="subscription_main_text">Дата окончания Вашей подписки</p>
        </div>
        <a href="#"><img src="{% static 'bg-elements/subscription.svg' %}" alt="Subscribe"></a>

        {% if user.is_paid and user.is_authenticated %}
            <div class="subscription_cancel">
                <a href="#" class="subscription_main_text subscription_cancel_link">Отменить подписку</a>
            </div>
        {% endif %}
    </div>
    <img src="{% static 'bg-elements/ellipse-26.svg' %}" alt="ellipse" class="ellipse-26">
{% endblock %}

templates/profile/unpaid_users.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}
{% endblock navbar %}

{% block content %}
    <div class="container page-container">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Username</th>
              <th scope="col">Имя Фамилия</th>
              <th scope="col">Дата рег-и</th>
            </tr>
          </thead>
          <tbody>

        {% for user in unpaid_users %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'profile' user.user.pk %}">{{ user.user.username }}</a></td>
                <td>{{ user.user.first_name }} {{ user.user.last_name }}</td>
                <td>{{ user.created_at| date }}</td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}

templates/profile/users.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}
{% endblock navbar %}

{% block content %}
    <div class="container page-container">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Username</th>
              <th scope="col">Имя Фамилия</th>
              <th scope="col">Дата рег-и</th>
            </tr>
          </thead>
          <tbody>

        {% for user in users %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'profile' user.user.pk %}">{{ user.user.username }}</a></td>
                <td>{{ user.user.first_name }} {{ user.user.last_name }}</td>
                <td>{{ user.created_at| date }}</td>
            </tr>
        {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}