api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import QuestionsViewSet, UsersViewSet, AnswerViewSet

router = routers.DefaultRouter()
router.register('questions', QuestionsViewSet)
router.register('users', UsersViewSet)
router.register('answers', AnswerViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('med.urls')),
    path('', include('accounts.urls')),
    path('', IndexView.as_view(), name='index'),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med/urls.py
from django.urls import path

from med.views.comment_views import CommentDeleteView, CommentListView, CommentModerationView, QuestionListView
from med.views.info_page import AboutMeView, OnlineConsultationView, OfflineConsultationView, AboutClubView
from med.views.photo_views import (
    PhotoCreateView, PhotoListView, PhotoDeleteView,
    PhotoDetailView, PhotoUpdateView
)

from med.views.search_view import search_view
from med.views.video_views import (
    VideoDetailView, Videos,
    AdminVideosList, VideoUpdate, VideoDeleteView
)

from med.views.article_views import (
    ArticleDeleteView, ArticleUpdateView, ArticleCreateView,
    ArticleDetailView, ArticleListView
)

from med.views.category_views import (
    CategoryListView, CategoryCreateView, CategoryDeleteView,
    CategoryEditView, CategoryArticleListView, CategoryPhotoListView,
    CategoryVideoListView
)


app_name = 'med'

urlpatterns = [
    # Video
    path('video/<int:pk>/', VideoDetailView.as_view(), name='video_detail'),
    # path('video/create/', VideoCreateView.as_view(), name='video_create'),
    path('videos/unpublished/', AdminVideosList.as_view(), name='videos_unpublished'),
    path('videos/', Videos.as_view(), name='videos'),
    path('video/<int:pk>/update/', VideoUpdate.as_view(), name='video_update'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='video_delete'),

    # Article
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),

    # Category
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category/<int:pk>/edit', CategoryEditView.as_view(), name='category_update'),
    path('category/<int:pk>/article/list', CategoryArticleListView.as_view(), name='category_article_list'),
    path('category/<int:pk>/photo/list', CategoryPhotoListView.as_view(), name='category_photo_list'),
    path('category/<int:pk>/video/list', CategoryVideoListView.as_view(), name='category_video_list'),

    # Photo
    path('photo/create', PhotoCreateView.as_view(), name='photo_create'),
    path('photo/list', PhotoListView.as_view(), name='photo_list'),
    path('photo/<int:pk>/delete', PhotoDeleteView.as_view(), name='photo_delete'),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
    path('photo/<int:pk>/update', PhotoUpdateView.as_view(), name='photo_update'),

    # Comment
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete'),
    path('comments/list', CommentListView.as_view(), name='comment_list'),
    path('questions/list', QuestionListView.as_view(), name='questions_list'),
    path('comment/<int:pk>/detail', CommentModerationView.as_view(), name='comment_detail'),

    # Others
    path('search/', search_view, name='search'),
    path('about_me/', AboutMeView.as_view(), name='about_me'),
    path('online_consultation/', OnlineConsultationView.as_view(), name='online_consultation'),
    path('offline_consultation/', OfflineConsultationView.as_view(), name='offline_consultation'),
    path('about_club/', AboutClubView.as_view(), name='about_club'),
]

med/models.py
from django.contrib.auth import get_user_model
from django.db import models
from embed_video.fields import EmbedVideoField


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название категории')
    is_main = models.BooleanField(default=False)
    main_category = models.ForeignKey(
        'self', null=True, blank=True, related_name='subcategories', on_delete=models.CASCADE)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['-title', ]


class Content(models.Model):
    title = models.CharField(max_length=1500, unique=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')

    class Meta:
        abstract = True


class Video(Content):
    picture = models.TextField(null=True, blank=True, verbose_name='Картинка')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    video_link = EmbedVideoField(max_length=10000, verbose_name='Ссылка видео', unique=True)
    categories = models.ManyToManyField('med.Category', related_name='video_categories')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at', ]


class Article(Content):
    subtitle = models.TextField(max_length=1000, null=True, verbose_name='Подзаголовок')
    picture = models.ImageField(upload_to='article_pics', verbose_name='Картинка')
    body = models.TextField(verbose_name='Тело статьи')
    categories = models.ManyToManyField('med.Category', related_name='article_categories')

    def __str__(self):
        return f'{self.title}, {self.created_at}'


class Photo(Content):
    image = models.ImageField(null=False, blank=False, upload_to='image_content', verbose_name='Фото')
    categories = models.ManyToManyField('med.Category', related_name='photo_categories')

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, null=True, blank=True, related_name='comment', on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, null=True, blank=True, related_name='comment', on_delete=models.CASCADE)
    video = models.ForeignKey(Video, null=True, blank=True, related_name='comment', on_delete=models.CASCADE)
    author = models.ForeignKey(get_user_model(), related_name='comment', on_delete=models.CASCADE,
                               verbose_name='Автор')
    body = models.TextField(max_length=2000, null=False, blank=False, verbose_name='Коментарий')
    is_anonymous = models.BooleanField(default=False)
    is_question = models.BooleanField(default=False)
    is_review = models.BooleanField(default=False)
    is_moderated = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.id}. {self.author}'

    class Meta:
        ordering = ['-created_at', ]


class Answer(models.Model):
    comment = models.ForeignKey(Comment, related_name='answer_comment',
                                on_delete=models.CASCADE, verbose_name='Ответ')
    author = models.ForeignKey(get_user_model(), related_name='answer', on_delete=models.CASCADE,
                               verbose_name='Автор')
    body = models.TextField(max_length=2000, null=False, blank=False, verbose_name='Ответ')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.id} {self.author}'

med/views/category_views.py
import json
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from med.models import Category, Article, Photo, Video
from med.forms import CategoryForm
from med.views.photo_views import DateTimeEncoder
from helpers.color_distribution import color_distribution, COLORS
from accounts.views.helpers import AdminPermissionsView


class CategoryListView(ListView):
    template_name = 'categories/categories_list.html'
    model = Category
    context_object_name = 'categories'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj_with_colors'] = color_distribution(Category.objects.all())
        context['colors'] = COLORS
        context['qs_cat'] = json.dumps(list(Category.objects.values()), cls=DateTimeEncoder)
        return context

    def post(self, *args, **kwargs):
        data = []
        response = None
        not_found = None
        context = {}
        html = ''
        category = self.request.POST.get('category')
        content_type = self.request.POST.get('content_type')

        if content_type == 'articles':
            data = Article.objects.filter(categories=category)
            html = 'article/articles_list.html'
        elif content_type == 'photos':
            data = Photo.objects.filter(categories=category)
            html = 'photo/photo_list.html'
        elif content_type == 'videos':
            data = Video.objects.filter(categories=category)
            html = 'video/videos.html'

        if len(data) > 0:
            response = data
        else:
            not_found = 'Not found...'

        context['obj_with_colors'] = color_distribution(Category.objects.all())
        context['colors'] = COLORS
        context['qs_cat'] = json.dumps(list(Category.objects.values()), cls=DateTimeEncoder)
        context['data'] = data
        context['not_found'] = not_found
        context['search_cat'] = Category.objects.get(id=category)
        context['search_categories'] = True

        return render(self.request, html, context=context)


class CategoryCreateView(AdminPermissionsView, CreateView):
    template_name = 'categories/create_category.html'
    model = Category
    form_class = CategoryForm

    def get_success_url(self):
        return reverse('med:categories')


class CategoryDeleteView(AdminPermissionsView, DeleteView):
    model = Category
    context_object_name = 'category'
    success_url = reverse_lazy('med:categories')


class CategoryEditView(AdminPermissionsView, UpdateView):
    template_name = 'categories/update_category.html'
    model = Category
    form_class = CategoryForm
    context_object_name = 'category'

    def get_success_url(self):
        return reverse('med:categories')


class CategoryArticleListView(DetailView):
    template_name = 'categories/article_category_list.html'
    model = Category
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.filter(categories=self.object)
        return context


class CategoryPhotoListView(DetailView):
    template_name = 'categories/photo_category_list.html'
    model = Category
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = Photo.objects.filter(categories=self.object)
        return context


class CategoryVideoListView(DetailView):
    template_name = 'categories/video_category_list.html'
    model = Category
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['video'] = Video.objects.filter(categories=self.object)
        return context

templates/categories/article_category_list.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}

{% block content %}
    <div class="container">
        <ol class="list-group list-group-numbered">
            {% for article in articles %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">
                            <a href="{% url 'med:article_detail' article.pk %}">{{ article.title }}</a>
                        </div>
                        {{ article.subtitle }}
                    </div>
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

templates/categories/categories.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Список категорий
{% endblock %}

{% block content %}
    <div class="container my-3">
        <div class="accordion" id="accordionExample">
            {% for category in categories %}
                <div class="accordion-item" style="border-color: {{ color }}">
                    <h2 class="accordion-header" id="headingOne{{ category.pk }}">
                        <button class="accordion-button"  style="border-color: {% cycle '#A2D9F7' '#B2A2C6' '#7ACFC8' '#F5B2B6' '#E9AED2' as color %}; background-color: {{ color }}" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{ category.pk }}" aria-expanded="true" aria-controls="collapseOne{{ category.pk }}">
                            {{ category.title }}
                            {% if perms.med.change_category %}
                             <a href="{% url 'med:category_update' category.pk %}"><i class="bi bi-pencil-square"></i></a>
                            {% endif %} 
                           {% if perms.med.delete_category %}
                            <form method="POST" action="{% url "med:category_delete" category.pk %}">
                                {% csrf_token %}
                                <input type="submit" class="bnt btn-danger btn-sm" value="Удалить">
                            </form>
                           {% endif %} 

                        </button>
                    </h2>
                    <div id="collapseOne{{ category.pk }}" class="accordion-collapse collapse" aria-labelledby="headingOne{{ category.pk }}" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <ol>
                                <li><a href="{% url 'med:category_article_list' category.pk %}">Статьи</a></li>
                                <li><a href="{% url 'med:category_photo_list' category.pk %}">Галерея</a></li>
                                <li> <a href="{% url 'med:category_video_list' category.pk %}">Видеоархив</a></li>
                            </ol>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% if perms.med.add_category %}
    <a class="btn btn-warning mt-3" href="{% url 'med:category_create' %}">Добавить новую категорию</a>
    {% endif %}

    </div>
{% endblock %}

templates/categories/categories_list.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Список категорий
{% endblock %}

{% block navbar %}
    {% include 'partial/navigation_new.html' %}
{% endblock %}

{% block content %}

    <h5 class="category-head">Выбрать актуальные темы</h5>

    {% include 'partial/search_categories_form.html' %}

    <script>window.__INITIALSTATE__ = '{{qs_cat}}'</script>
    <script>let colors = '{{ colors }}'</script>
    <script src="{% static 'js/search.js' %}"></script>

{% endblock %}

templates/categories/create_category.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}

{% block content %}
    <div class="container">
        <h2>Добавить новую категорию</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}

        <div class="mb-3">
          <label for="title" class="form-label">Название категории</label>
          <input type="text" class="form-control form-control-sm" id="title" name="title">
        </div>
        <button type="submit" class="btn btn-secondary">Опубликовать</button>
    </form>

    </div>
{% endblock %}

templates/categories/photo_category_list.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}

{% block content %}
    <div class="container">
        <ol class="list-group list-group-numbered">
            {% for photo in photos %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">
                            <a href="{% url 'med:photo_detail' photo.pk %}">{{ photo.title }}</a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

templates/categories/update_category.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}

{% block content %}
    <div class="container">
        <h2>Изменить категорию</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}

        <div class="mb-3">
          <label for="title" class="form-label">Название категории</label>
          <input type="text" class="form-control form-control-sm" id="title" name="title" value="{{ category.title }}">
        </div>
        <button type="submit" class="btn btn-secondary">Сохранить</button>
    </form>

    </div>
{% endblock %}

templates/categories/video_category_list.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}

{% block content %}
<div class="container">
<ol class="list-group list-group-numbered">
    {% for vid in video %}
         <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold"><a href="{% url 'med:video_detail' vid.pk %}">{{ vid.title }}</a></div>
      {{ vid.description }}
    </div>
  </li>
    {% endfor %}
</ol>
</div>
{% endblock %}