api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import QuestionsViewSet, UsersViewSet, AnswerViewSet

router = routers.DefaultRouter()
router.register('questions', QuestionsViewSet)
router.register('users', UsersViewSet)
router.register('answers', AnswerViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('med.urls')),
    path('', include('accounts.urls')),
    path('', IndexView.as_view(), name='index'),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med/urls.py
from django.urls import path

from med.views.comment_views import CommentDeleteView, CommentListView, CommentModerationView, QuestionListView
from med.views.info_page import AboutMeView, OnlineConsultationView, OfflineConsultationView, AboutClubView
from med.views.photo_views import (
    PhotoCreateView, PhotoListView, PhotoDeleteView,
    PhotoDetailView, PhotoUpdateView
)

from med.views.search_view import search_view
from med.views.video_views import (
    VideoDetailView, Videos,
    AdminVideosList, VideoUpdate, VideoDeleteView
)

from med.views.article_views import (
    ArticleDeleteView, ArticleUpdateView, ArticleCreateView,
    ArticleDetailView, ArticleListView
)

from med.views.category_views import (
    CategoryListView, CategoryCreateView, CategoryDeleteView,
    CategoryEditView, CategoryArticleListView, CategoryPhotoListView,
    CategoryVideoListView
)


app_name = 'med'

urlpatterns = [
    # Video
    path('video/<int:pk>/', VideoDetailView.as_view(), name='video_detail'),
    # path('video/create/', VideoCreateView.as_view(), name='video_create'),
    path('videos/unpublished/', AdminVideosList.as_view(), name='videos_unpublished'),
    path('videos/', Videos.as_view(), name='videos'),
    path('video/<int:pk>/update/', VideoUpdate.as_view(), name='video_update'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='video_delete'),

    # Article
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),

    # Category
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category/<int:pk>/edit', CategoryEditView.as_view(), name='category_update'),
    path('category/<int:pk>/article/list', CategoryArticleListView.as_view(), name='category_article_list'),
    path('category/<int:pk>/photo/list', CategoryPhotoListView.as_view(), name='category_photo_list'),
    path('category/<int:pk>/video/list', CategoryVideoListView.as_view(), name='category_video_list'),

    # Photo
    path('photo/create', PhotoCreateView.as_view(), name='photo_create'),
    path('photo/list', PhotoListView.as_view(), name='photo_list'),
    path('photo/<int:pk>/delete', PhotoDeleteView.as_view(), name='photo_delete'),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
    path('photo/<int:pk>/update', PhotoUpdateView.as_view(), name='photo_update'),

    # Comment
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete'),
    path('comments/list', CommentListView.as_view(), name='comment_list'),
    path('questions/list', QuestionListView.as_view(), name='questions_list'),
    path('comment/<int:pk>/detail', CommentModerationView.as_view(), name='comment_detail'),

    # Others
    path('search/', search_view, name='search'),
    path('about_me/', AboutMeView.as_view(), name='about_me'),
    path('online_consultation/', OnlineConsultationView.as_view(), name='online_consultation'),
    path('offline_consultation/', OfflineConsultationView.as_view(), name='offline_consultation'),
    path('about_club/', AboutClubView.as_view(), name='about_club'),
]

med/views/video_views.py
import logging

import json
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from helpers.color_distribution import color_distribution, COLORS
from helpers.date_time_encoder import DateTimeEncoder
from med.forms import VideoForm, CommentForm, AnswerForm
from med.models import Video, Category
import vimeo
from accounts.views.helpers import AdminPermissionsView
from mixins.content_post import ContentPostMixin

logger = logging.getLogger('main')


# List of unpublished videos. Sends a request to the Vimeo API,
# returns a list of videos that are not in the database. Available to admin.
# Adding videos from the list of unpublished videos to the database.


class AdminVideosList(AdminPermissionsView, CreateView):
    permission_required = ['add_video', ]
    template_name = 'video/video_list_admin.html'
    model = Video
    form = VideoForm
    fields = ['title', 'description', 'video_link', 'categories', 'picture']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        client = vimeo.VimeoClient(
            token='7cd9746491c6faea34760c6ce1ab19c2',
            key='b28a965f89a399303309e09106540176a9aea49f',
            secret='exQIToFUrBTbiQUHFgi6Fq0icQSLzfcNn2w/'
                   'prppKBOJPnA8cJQwIqAILLZPU7/idUOqh/'
                   'XZuzv5iCYggBX7o20a03yv2mI8O3OFuFDoeGP/bkIUY2zG7eCf8OipLBXz'
        )

        response = client.get('https://api.vimeo.com/me/videos/')
        video_links = Video.objects.filter().values('video_link')

        list_val = []

        for i in list(video_links):
            for key, val in i.items():
                list_val.append(val)

        context['videos'] = response.json().get('data')
        context['categories'] = Category.objects.all()
        context['video_links_saved'] = list_val
        return context

    def get_success_url(self):
        return reverse('med:videos')

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


# The view for the video detail page. Displays all information about the video,
# and there is also a form for a question.

class VideoDetailView(LoginRequiredMixin, DetailView):
    template_name = 'video/video_detail.html'
    context_object_name = 'video'
    model = Video

    def get(self, request, *args, **kwargs):
        video = self.get_object()
        logger.info(f'Пользователь {self.request.user} был на странице и просмотрел видео: {video.title}.')
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(self.request.POST)
        answer_form = AnswerForm(self.request.POST)
        video = get_object_or_404(Video, pk=self.kwargs.get('pk'))

        if 'question_send' in self.request.POST:
            if comment_form.is_valid():
                question = comment_form.save(commit=False)
                question.author = self.request.user
                question.video_id = video.pk
                question.is_question = True
                if request.POST.get('is_anonymous'):
                    question.is_anonymous = True
                question.save()

        elif 'answer_send' in self.request.POST:
            if answer_form.is_valid():
                answer = answer_form.save(commit=False)
                answer.author = self.request.user
                answer.save()

        return redirect('med:video_detail', pk=kwargs.get('pk'))


# List of published videos from the database.

class Videos(LoginRequiredMixin, ListView, ContentPostMixin):
    model = Video
    template_name = 'video/videos.html'
    context_object_name = 'videos'

    def get_queryset(self):
        return Video.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['obj_with_colors'] = color_distribution(Category.objects.all())
        context['colors'] = COLORS
        context['qs_cat'] = json.dumps(list(Category.objects.values()), cls=DateTimeEncoder)
        return context


# Video editing.

class VideoUpdate(AdminPermissionsView, UpdateView):
    permission_required = ['change_video', ]
    template_name = 'video/video_update.html'
    form_class = VideoForm
    model = Video
    context_object_name = 'v'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['categories'] = Category.objects.all()
        return context

    def get_success_url(self):
        return reverse('med:video_detail', kwargs={'pk': self.object.pk})


# Video Deleting from Database.

class VideoDeleteView(AdminPermissionsView, DeleteView):
    permission_required = ['delete_video', ]
    template_name = 'video/video_delete.html'
    model = Video
    context_object_name = 'video'
    success_url = reverse_lazy('med:videos')

templates/video/video_create_sidebar.html
{% if v %}
    {% for category in categories %}
        {% if category.pk in v.categories %}

            <div class="form-check">
                <input class="form-check-input" checked name="categories" value="{{ category.pk }}" type="checkbox" id="{{ category.pk }}">
                <label class="form-check-label" for="{{ category.pk }}">{{ category.title }}</label>
            </div>

        {% endif %}
    {% endfor %}

    {% for category in categories %}
        {% if category.pk not in v.categories %}

            <div class="form-check">
                <input class="form-check-input" name="categories" value="{{ category.pk }}" type="checkbox" id="{{ category.pk }}">
                <label class="form-check-label" for="{{ category.pk }}">{{ category.title }}</label>
            </div>

        {% endif %}
    {% endfor %}

{% else %}

    {% for category in categories %}
        <div class="form-check">
            <input class="form-check-input" name="categories" value="{{ category.pk }}" type="checkbox" id="{{ category.pk }}">
            <label class="form-check-label" for="{{ category.pk }}">{{ category.title }}</label>
        </div>
    {% endfor %}

{% endif %}

templates/video/video_delete.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Удаление видео
{% endblock %}


{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}

{% block content %}
    <div class="container">
    <form method="POST" action="{% url "med:video_delete" video.pk %}">
        {% csrf_token %}
        <p>Вы дейтвительно хотите удалить видео: "{{ video.title }}"?</p>
        <input type="submit" class="btn btn-danger" value="Удалить">
        <a href="{% url 'med:videos' %}" class="btn btn-primary">Вернуться к списку видео</a>
    </form>
    </div>
{% endblock %}

templates/video/video_detail.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Просмотр видео
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}
{% load embed_video_tags %}

{% block content %}
    <div class="container">
        <hr>
        <a href="{% url 'med:videos' %}">
            <div style="border-radius: 50%; width: 30px; height: 30px; left: 38px; top: 140px; background: #FCD5A6;">
                <img src="{% static 'bg-elements/arrow-right.svg' %}" alt="Arrow left" class="drobtn_img" style="margin-left: 8px">
            </div>
        </a>

        <div class="video-wrapp">
            {% video video.video_link '355x660' %}
        </div>

        <h5><b>{{ video.title }}</b></h5>
        {% if not video.description == 'None' %}
            <p style="font-size: 18px">{{ video.description }}</p>
        {% endif %}

        {% if user.profile.is_admin or user.is_superuser %}
            <a href="{% url 'med:video_update' video.pk %}" class="btn btn-sm" style="color:white; width: 100%; background-color: #B2A2C6">Редактировать</a>
        {% endif %}

        {% if user.profile.is_admin or user.is_superuser %}
            <a href="{% url 'med:video_delete' video.pk %}" class="btn btn-danger btn-sm mt-2" style="width: 100%">Удалить</a>
        {% endif %}

        <div class="flex-wrapp comment-btn-wrapp">
            <button id="modal-btn" class="send-question-btn">
                Добавить комментарий
            </button>
        </div>

        {% url 'med:video_detail' video.pk as url %}

    </div>

    <hr>

    <div id="container">
        {% for com in video.comment.all %}

            {% if com.is_deleted == False %}
                {% if not com.is_moderated and user == com.author or com.author.profile.is_admin or user.is_superuser %}
                    {% include 'partial/comments_list.html' %}

                {% elif com.is_anonymous and user == com.author or com.author.profile.is_admin or user.is_superuser  %}
                    {% include 'partial/comments_list.html' %}

                {% elif com.is_moderated and not com.is_anonymous %}
                    {% include 'partial/comments_list.html' %}

                {% endif %}
            {% endif %}

        {% endfor %}
        </div>

    <input type="hidden" id="content" data-content-type="video" value="{{ video.id }}">

    <div hidden id="modal-form" class="modal-form hidde-modal">
            {% csrf_token %}

            <textarea name="body" id="body" cols="30" rows="7"></textarea>

            <div id="anonymous-btn">
                <div class="hidde-anonymous-text" id="anonymous-btn-text">Виден только администратору</div>

                <div id="anonymous-btn-body">
                    <i class="bi bi-incognito"></i>
                </div>
            </div>

            <input type="hidden" id="user-pk" value="{{ user.pk }}">
            <input type="hidden" id="question-pk" value="">
            <input type="hidden" id="anonymous" value="">

    </div>

    <div hidden id="btn-send" class="move-to-hide disabled" data-comment="True">
        <div id="send-flash" class="flashing-on">
            <img src="{% static 'bg-elements/send-question.svg' %}" alt="" class="btn-icon">
        </div>
    </div>

    <div hidden id="btn-add" class="move-to-hide disabled" data-comment="True">
        <div id="add-flash" class="flashing-on">
            <img src="{% static 'bg-elements/complement-question.svg' %}" alt="" class="btn-icon">
        </div>
    </div>

    <div hidden id="send-bg" class="modal-bg to-light disabled"></div>
    <div hidden id="add-bg" class="modal-bg to-light disabled"></div>

    <script src="{% static 'js/comments.js' %}"></script>
{%endblock%}

templates/video/video_list_admin.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Список видео
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}
{% load embed_video_tags %}

{% block content %}
    <div class="container page-container">
        <h1>Неопубликованные Видео</h1>
		<hr>
		{% for v in videos %}
            {% if v.link not in video_links_saved %}

                {% video v.link '355x670' %}
                <h5><b>{{ v.name }}</b></h5>

                <form action="{% url 'med:videos_unpublished' %}" method="post">
                    {% csrf_token %}
                    {% for error in form.non_field_errors %}
                        <p class="form-error">{{ error }}</p>
                    {% endfor %}
                    <input type="hidden" name="picture" value="{{ v.pictures.base_link }}">
                    <input type="hidden" name="title" value="{{ v.name }}">
                    <input type="hidden" name="description" value="{{ v.description }}">
                    <input type="hidden" name="video_link" value="{{ v.link }}">

                    <div class="flex_wrapp">
                        <button class="btn btn-sm width-100" type="button" data-bs-toggle="offcanvas"
                                data-bs-target="#link{{ forloop.counter }}" aria-controls="offcanvasRight"
                                style="background-color: #FCD5A6; width: 100%;">
                            Добавить категории
                        </button>

                        {% if form.errors.categories %}
                            <div class="alert alert-danger errors-list text_center" role="alert">
                                {% for error in form.errors.categories %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>

                    <div class="offcanvas offcanvas-end" tabindex="-1" id="link{{forloop.counter }}" aria-labelledby="offcanvasRightLabel">
                        <div class="offcanvas-header sidebar-header">
                            <h5 id="offcanvasRightLabel">Список категорий</h5>
                            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>

                        <div class="offcanvas-body">
                            {% include 'video/video_create_sidebar.html' %}
                        </div>
                    </div>


                    <input class="btn btn-sm mt-2" type="submit" value="Опубликовать" style="color:white; width: 100%; background-color: #B2A2C6">
                </form>
                <hr/>

            {% endif %}
		{% endfor %}
    </div>
{%endblock%}

templates/video/video_update.html
{% extends 'base_new.html' %}
{% load static %}

{% block title %}
    Редактирование видео
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}
{% endblock navbar %}

{% block content %}
    <div class="container page-container">
        <h2>Внести изменения в видео</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="video_link" value="{{ v.video_link }}">
            <div class="mb-3">
                <label for="title" class="form-label">Название*</label>
                <input type="text" class="form-control form-control-sm" id="title" name="title" value="{{ v.title }}">

                {% if form.errors.title %}
                    <div class="alert alert-danger errors-list text_center" role="alert">
                        {% for error in form.errors.title %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="description" class="form-label">Описание</label>
                <textarea class="form-control form-control-sm" id="description" rows="5" name="description">{{ v.description }}</textarea>
                {% if form.errors.description %}
                    <div class="alert alert-danger errors-list text_center" role="alert">
                        {% for error in form.errors.description %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="flex_wrapp">
                {% if form.errors.categories %}
                    <button class="btn btn-sm width-100" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"
                            style="background-color: #FCD5A6; width: 100%; border: 1px solid red">
                        Добавить категории
                    </button>
                    <div class="alert errors-list error_style" role="alert" style="margin-left: 0">
                        {% for error in form.errors.categories %}
                            <span>*</span>{{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    <button class="btn btn-sm width-100" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"
                            style="background-color: #FCD5A6; width: 100%">
                        Добавить категории
                    </button>
                {% endif %}
            </div>

            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
                <div class="offcanvas-header sidebar-header">
                    <h5 id="offcanvasRightLabel">Список категорий</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>

                <div class="offcanvas-body">
                    {% block sidebar %}
                        {% for category in categories %}
                            {% if category in article.categories.all %}
                            <div class="form-check">
                                <input class="form-check-input" checked name="categories" value="{{ category.pk }}" type="checkbox" id="{{ category.pk }}">
                                <label class="form-check-label" for="{{ category.pk }}">{{ category.title }}</label>
                            </div>
                            {% endif %}
                        {% endfor %}

                        {% for category in categories %}
                            {% if not category in article.categories.all %}
                            <div class="form-check">
                                <input class="form-check-input" name="categories" value="{{ category.pk }}" type="checkbox" id="{{ category.pk }}">
                                <label class="form-check-label" for="{{ category.pk }}">{{ category.title }}</label>
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endblock %}
                </div>
            </div>

            <button type="submit" class="btn btn-sm mt-2" style="background-color: #B2A2C6; color: white; width: 100%">
                    Опубликовать
            </button>
        </form>
    </div>
{% endblock %}

templates/video/videos.html
{% extends 'base_new.html' %}
{% load static %}
{% load embed_video_tags %}

{% block title %}
    Список видео
{% endblock %}

{% block navbar %}
    {% include 'partial/navigation_new.html' %}
{% endblock %}

{% block content %}
    {% if search_categories %}
        {% include 'partial/search_categories_form.html' %}
    {% else %}
        {% include 'partial/search_content_form.html' %}
    {% endif %}

        {% if user.profile.is_admin or user.is_superuser %}

            <div class="go-unpublished-videos">
                <a href="{% url 'med:videos_unpublished' %}">
                    <b><i class="bi bi-arrow-left-circle"></i> Перейти к списку неопубликованных видео</b>
                </a>
            </div>

        {% endif %}

        {% if not_found %}

            <div class="not-found">
                <b>Ни одного видео с категорией '{{ search_cat }}' не найдено...</b>
            </div>

        {% elif data %}
            <div class="btn-cat find-cat">
                {{ search_cat }}
            </div>
            <hr>

            {% for v in data %}
                <div class="gap-3 flex-wrapp">
                    {% video v.video_link '100x200' %}
                    <div style="width: 50%">
                        <h5 style="margin-top: 20px"><b><a href="{% url 'med:video_detail' v.pk %}">{{ v.title }}</a></b></h5>
                            {% for cat in v.categories.all %}
                                <p class="vide_cat_title">{{ cat }}</p>
                            {% endfor %}

                        <a href="{% url 'med:video_detail' v.pk %}" class="btn btn-sm mt-2" style="color:white; width: 100%; background-color: #B2A2C6">
                            Перейти
                        </a>
                    </div>
                </div>

                <hr/>
            {% endfor %}

        {% else %}

            {% for v in videos %}
                <div class="gap-3 flex-wrapp">
                    {% video v.video_link '100x200' %}
                    <div style="width: 50%">
                        <h5 style="margin-top: 20px"><b><a href="{% url 'med:video_detail' v.pk %}">{{ v.title }}</a></b></h5>
                        {% for cat in v.categories.all %}
                            <p class="vide_cat_title">{{ cat }}</p>
                        {% endfor %}

                        <a href="{% url 'med:video_detail' v.pk %}" class="btn btn-sm mt-2" style="color:white; width: 100%; background-color: #B2A2C6">
                            Перейти
                        </a>
                    </div>
                </div>

                <hr/>
            {% endfor %}

        {% endif %}

        <img src="{% static 'bg-elements/ellipse-34.svg' %}" class="ellipse-34" alt="">
		<hr>
        <img src="{% static 'bg-elements/ellipse-35.svg' %}" class="ellipse-35" alt="">

    <script>window.__INITIALSTATE__ = '{{qs_cat}}'</script>
    <script>let colors = '{{ colors }}'</script>
    <script src="{% static 'js/search.js' %}"></script>

{% endblock %}