api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import QuestionsViewSet, UsersViewSet, AnswerViewSet

router = routers.DefaultRouter()
router.register('questions', QuestionsViewSet)
router.register('users', UsersViewSet)
router.register('answers', AnswerViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('med.urls')),
    path('', include('accounts.urls')),
    path('', IndexView.as_view(), name='index'),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med/urls.py
from django.urls import path

from med.views.comment_views import CommentDeleteView, CommentListView, CommentModerationView, QuestionListView
from med.views.info_page import AboutMeView, OnlineConsultationView, OfflineConsultationView, AboutClubView
from med.views.photo_views import (
    PhotoCreateView, PhotoListView, PhotoDeleteView,
    PhotoDetailView, PhotoUpdateView
)

from med.views.search_view import search_view
from med.views.video_views import (
    VideoDetailView, Videos,
    AdminVideosList, VideoUpdate, VideoDeleteView
)

from med.views.article_views import (
    ArticleDeleteView, ArticleUpdateView, ArticleCreateView,
    ArticleDetailView, ArticleListView
)

from med.views.category_views import (
    CategoryListView, CategoryCreateView, CategoryDeleteView,
    CategoryEditView, CategoryArticleListView, CategoryPhotoListView,
    CategoryVideoListView
)


app_name = 'med'

urlpatterns = [
    # Video
    path('video/<int:pk>/', VideoDetailView.as_view(), name='video_detail'),
    # path('video/create/', VideoCreateView.as_view(), name='video_create'),
    path('videos/unpublished/', AdminVideosList.as_view(), name='videos_unpublished'),
    path('videos/', Videos.as_view(), name='videos'),
    path('video/<int:pk>/update/', VideoUpdate.as_view(), name='video_update'),
    path('video/<int:pk>/delete/', VideoDeleteView.as_view(), name='video_delete'),

    # Article
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),

    # Category
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category/<int:pk>/edit', CategoryEditView.as_view(), name='category_update'),
    path('category/<int:pk>/article/list', CategoryArticleListView.as_view(), name='category_article_list'),
    path('category/<int:pk>/photo/list', CategoryPhotoListView.as_view(), name='category_photo_list'),
    path('category/<int:pk>/video/list', CategoryVideoListView.as_view(), name='category_video_list'),

    # Photo
    path('photo/create', PhotoCreateView.as_view(), name='photo_create'),
    path('photo/list', PhotoListView.as_view(), name='photo_list'),
    path('photo/<int:pk>/delete', PhotoDeleteView.as_view(), name='photo_delete'),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
    path('photo/<int:pk>/update', PhotoUpdateView.as_view(), name='photo_update'),

    # Comment
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment_delete'),
    path('comments/list', CommentListView.as_view(), name='comment_list'),
    path('questions/list', QuestionListView.as_view(), name='questions_list'),
    path('comment/<int:pk>/detail', CommentModerationView.as_view(), name='comment_detail'),

    # Others
    path('search/', search_view, name='search'),
    path('about_me/', AboutMeView.as_view(), name='about_me'),
    path('online_consultation/', OnlineConsultationView.as_view(), name='online_consultation'),
    path('offline_consultation/', OfflineConsultationView.as_view(), name='offline_consultation'),
    path('about_club/', AboutClubView.as_view(), name='about_club'),
]

templates/partial/comments_list.html
{% load static %}

<div class="container">
    <div class="gap-2 flex-wrapp">
        <div class="comment-ring">
            <img class="author-no-avatar" src="{% static 'bg-elements/photo.svg' %}" alt="">
        </div>
        <div style="width: 80%">
            <p style="font-size: 16px; margin-bottom: 1px"><b>{{ com.author.first_name }} {{ com.author.last_name }}</b></p>

            <p class="card-subtitle text-muted" style="font-size: 12px">
                {{ com.created_at }}

                {% if not com.is_moderated and user.is_superuser or user.profile.is_admin %}
                    ---<a class="moderation-text" href="{% url 'med:comment_detail' com.pk %}"> на модерации</a>
                {% elif not com.is_moderated %}
                    ---<span class="moderation-text"> на модерации</span>
                {% endif %}

                {% if com.is_anonymous %}
                    <span class="anonymous-icon">
                        <i class="bi bi-incognito"></i>
                    </span>
                {% endif %}

            </p>
        </div>
    </div>
    <p style="font-size: 15px">{{ com.body }}</p>

    {% if com.is_moderated and user == com.author or com.is_moderated and user.profile.is_admin or user.is_superuser %}

        <div class="mb-2 add-comment-answer" data-target="addition" data-id="{{ com.id }}">
            {% if user.is_superuser or user.profile.is_admin %}
                ответить
            {% else %}
                дополнить
            {% endif %}
        </div>

    {% endif %}

</div>

<div id="answers-{{ com.id }}">
    {% for answer in com.answer_comment.all %}

        <div class="container">
            <div style="margin-left: 30px">
                <div class="gap-2 flex-wrapp">
                    <div class="comment-ring-answer">
                        <img class="author-no-avatar" src="{% static 'bg-elements/photo.svg' %}" alt="">
                    </div>
                    <div style="width: 80%">
                        <p style="font-size: 16px; margin-bottom: 1px">
                            <b>{{ answer.author.first_name }} {{ answer.author.last_name }}</b>

                            {% if answer.author.profile.is_admin %}
                                (администратор)
                            {% endif %}
                        </p>

                        <p class="card-subtitle text-muted" style="font-size: 12px">{{ answer.created_at }}</p>
                    </div>
                </div>
                <p style="font-size: 15px">{{ answer.body }}</p>
            </div>
        </div>

    {% endfor %}
</div>

<hr>

templates/partial/content_question.html
<section>
  <div class="popup-outer">
      <div class="popup-box">
        <h5 class="modal-title" id="comment-modal-form-label">Добавить комментарий</h5>
        <i id="close" class='bi bi-x close'></i>
            <form method="post" action="{{ url }}" id="question">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="mb-3">
                        <textarea name="body" class="form-control" id="comment-text"></textarea>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="is_anonymous" value="is_anonymous" id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                            Отобразить только для администратора
                        </label>
                    </div>
                </div>

                <div class="button">
                    <button id="close" class="cancel">Отменить</button>
                    <button type="submit" name="question_send" class="btn btn-sm btn-green send">Добавить</button>
                </div>
            </form>
      </div>
  </div>
</section>

templates/partial/form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}">
        {% csrf_token %}
{% endif %}

        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}

        {{ form.as_p }}

{% if not fields_only %}
        <br/>
        <input type="submit" value="{{ button_text|default:"Submit" }}"/>
    </form>
{% endif %}

templates/partial/include_navbar_base.html
{% extends 'base_new.html' %}
{% load static %}

{% block navbar %}
    {% if user.is_authenticated %}
        {% include 'partial/navigation_new.html' %}
        {% else %}
        {% include 'partial/mainpage_navbar.html' %}
    {% endif %}

{% endblock navbar %}

templates/partial/mainpage_navbar.html
{% load static %}

<div class="navigation">
    <div class="logo_mainpage">
        <div>
            <a href="{% url 'index' %}">
                <img class="logo_img" src="{% static 'bg-elements/logo.svg' %}" alt="логотип">
            </a>
        </div>
        <div class="block_login">
            <div class="login_btn">
                <a href="{% url 'login' %}" type="button">Войти</a>
            </div>
        </div>
    </div>
</div>

templates/partial/navigation_new.html
{% load static %}

<div class="navigation">

    <div class="logo">
        <a href="{% url 'index' %}">
            <img src="{% static 'bg-elements/logo.svg' %}" alt="">
        </a>
    </div>

    <div id="open" class="menu-btn">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
    </div>

    <div id="hide-bg" class="hidden-bg to-light" hidden></div>

    <div id="hide" class="hidden-menu" hidden>
        <div id="menu" class="menu to-hide">

            <a href="{% url 'index' %}">
                <img class="menu-logo" src="{% static 'bg-elements/logo.svg' %}" alt="">
            </a>

            <button id="close" class="menu-close">
                <img class="img-close" src="{% static 'bg-elements/menu-close.svg' %}" alt="">
            </button>

            <div class="menu-links">
                {% if user.profile.is_admin or user.is_superuser %}
                    <a class="menu-links-item menu-links-pink" href="{% url 'admin_site' %}">
                    <p class="menu-links-item-text">
                        Админ панель
                    </p>
                </a>
                {% endif %}

                {% if user.is_authenticated and not user.profile_is_admin and not user.is_superuser %}
                    <a class="menu-links-item menu-links-pink" href="{% url 'profile' pk=user.pk %}">
                        <p class="menu-links-item-text">
                            Личный кабинет
                        </p>
                    </a>
                {% endif %}

                <a class="menu-links-item menu-links-blue" href="{% url 'med:categories' %}">
                    <p class="menu-links-item-text">
                        Темы
                    </p>
                </a>

                <a class="menu-links-item menu-links-green-1" href="{% url 'med:videos' %}">
                    <p class="menu-links-item-text">
                        Видео - интервью с врачами
                    </p>
                </a>

                <a class="menu-links-item menu-links-pink-1" href="{% url 'med:photo_list' %}">
                    <p class="menu-links-item-text">
                        Сохранённые сторис
                    </p>
                </a>

                <a class="menu-links-item menu-links-pink" href="{% url 'med:articles' %}">
                    <p class="menu-links-item-text">
                        Публикации
                    </p>
                </a>

                <a class="menu-links-item menu-links-green-1" href="{% url 'med:offline_consultation' %}">
                    <p class="menu-links-item-text">
                        Очный приём
                    </p>
                </a>

                <a class="menu-links-item menu-links-pink" href="{% url 'med:online_consultation' %}">
                    <p class="menu-links-item-text">
                        Онлайн - консультации
                    </p>
                </a>

                <a class="menu-links-item menu-links-pink-1" href="https://www.instagram.com/hisamova_club/?utm_medium=copy_link">
                    <p class="menu-links-item-text">
                        Instagram
                    </p>
                </a>


                {% if user.is_authenticated %}
                     <a class="menu-links-item menu-links-green-1" href="{% url 'logout' %}">
                        <p class="menu-links-item-text">
                            Выйти
                        </p>
                    </a>
                {% endif %}
            </div>

        </div>
    </div>

</div>

templates/partial/search_categories_form.html
{% load static %}

<div class="input-wrapp">
    <input type="text" id="search" data-cat-list="true" placeholder="Начните вводить название">

    <div class="circle-cat">
        <img class="arrow" src="{% static 'bg-elements/arrow-down.svg' %}" alt="">
    </div>
</div>

<form method="post">
    {% csrf_token %}

    <input type="hidden" value="" name="content_type" id="content_type">

    <div class="box not-visible">
        <div class="category-container" id="container">
            {% for category, color in obj_with_colors %}
                {% if not category.main_category %}
                    <div class="btn-cat" data-id="{{ category.id }}" style="border-color: {{ color }}">
                        {{ category.title }}

                        <div class="submit-box" id="{{ category.id }}" style="border-color: {{ color }}">
                            <button type="submit" class="btn-submit" name="category" style="border-color: {{ color }}" data-content-type="videos" value="{{ category.id }}">Видео</button>
                            <button type="submit" class="btn-submit" name="category" style="border-color: {{ color }}" data-content-type="photos" value="{{ category.id }}">Сторис</button>
                            <button type="submit" class="btn-submit" name="category" style="border-color: {{ color }}" data-content-type="articles" value="{{ category.id }}">Публикации</button>
                        </div>

                    </div>

                    <br>

                {% endif %}

                {% if category.is_main %}
                    <div class="subcategories-box">
                        {% for subcategory, sub_cat_color in obj_with_colors %}

                            {% if subcategory.main_category == category %}
                                 <div class="btn-cat sub-cat" data-id="{{ subcategory.id }}" style="border-color: {{ color }}">
                                     {{ subcategory.title }}

                                    <div class="submit-box" id="{{ subcategory.id }}" style="border-color: {{ color }}">
                                        <button type="submit" class="btn-submit" name="category" style="border-color: {{ color }}" data-content-type="videos" value="{{ category.id }}">Видео</button>
                                        <button type="submit" class="btn-submit" name="category" style="border-color: {{ color }}" data-content-type="photos" value="{{ category.id }}">Сторис</button>
                                        <button type="submit" class="btn-submit" name="category" style="border-color: {{ color }}" data-content-type="articles" value="{{ category.id }}">Публикации</button>
                                    </div>

                                 </div>

                            {% endif %}

                            {% if forloop.last %}
                                <br>
                            {% endif %}

                        {% endfor %}
                    </div>
                {% endif %}

            {% endfor %}
        </div>
    </div>

</form>

templates/partial/search_content_form.html
{% load static %}

<div class="input-wrapp">
    <input type="text" id="search" name="search" placeholder="Начните вводить название">

    <div class="circle-cat">
        <img class="arrow" src="{% static 'bg-elements/arrow-down.svg' %}" alt="">
    </div>
</div>

<form method="post">
    {% csrf_token %}    

    <div class="box not-visible">
        <div class="category-container" id="container">
            {% for category, color in obj_with_colors %}
            {% if not category.main_category %}
                <input type="submit" class="btn-cat sub-cat" name="search" value="{{ category.title }}" style="border-color: {{ color }}">
                <br>
            {% endif %}

            {% if category.is_main %}
                <div class="subcategories-box">
                    {% for subcategory, sub_cat_color in obj_with_colors %}

                        {% if subcategory.main_category == category %}

                            <input type="submit" class="btn-cat sub-cat btn-submit" name="search" value="{{ subcategory.title }}" style="border-color: {{ color }}">

                        {% endif %}

                        {% if forloop.last %}
                            <br>
                        {% endif %}

                    {% endfor %}
                </div>
            {% endif %}

        {% endfor %}
        </div>
    </div>

</form>